import { Pager } from '@/components/Pager';

/* Home is section 0. Every other section has its own static route
   (`/work/`, `/research/`, …) generated by `app/[section]/page.tsx`. */
export default function Home() {
  return <Pager initialIndex={0} />;
}
