#!/usr/bin/env python3
"""Generate the hero world-map path data for components/world-map-path.ts.

Source: Natural Earth 1:110m physical land polygons (public domain),
fetched as GeoJSON. The map is the environment behind the hero name, so
it is deliberately low-fidelity: Miller projection, cropped to the
inhabited latitudes, Douglas-Peucker simplified, and rounded to 0.1px.

Regenerate:
    curl -sL -o /tmp/land.json https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/110m/physical/ne_110m_land.json
    python3 tools/make-worldmap.py

The output is committed, so the build never needs this script or network.
"""
import json
import math

SRC = "/tmp/land.json"
OUT = "components/world-map-path.ts"

W = 1000.0          # viewBox width in px (lon -180..180)
LAT_TOP, LAT_BOT = 84.0, -58.0   # crop: inhabited latitudes, no Antarctica
TOL = 0.9           # Douglas-Peucker tolerance in px
MIN_EXTENT = 2.2    # drop islands smaller than this in px


def miller_y(lat_deg):
    """Miller cylindrical northing, in px, relative to the equirect centre."""
    phi = math.radians(lat_deg)
    return -1.25 * math.log(math.tan(math.pi / 4 + 0.4 * phi)) * (W / (2 * math.pi))


def project(lon, lat):
    x = (lon + 180.0) / 360.0 * W
    return x, miller_y(lat)


def rdp(pts, tol):
    """Iterative Douglas-Peucker (recursion depth is unbounded on coastlines)."""
    if len(pts) < 3:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        i, j = stack.pop()
        if j <= i + 1:
            continue
        ax, ay = pts[i]
        bx, by = pts[j]
        dx, dy = bx - ax, by - ay
        seg2 = dx * dx + dy * dy
        best, bestk = -1.0, -1
        for k in range(i + 1, j):
            px, py = pts[k]
            if seg2 == 0:
                d2 = (px - ax) ** 2 + (py - ay) ** 2
            else:
                t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / seg2))
                qx, qy = ax + t * dx, ay + t * dy
                d2 = (px - qx) ** 2 + (py - qy) ** 2
            if d2 > best:
                best, bestk = d2, k
        if best > tol * tol:
            keep[bestk] = True
            stack.append((i, bestk))
            stack.append((bestk, j))
    return [p for p, k in zip(pts, keep) if k]


def rings(geom):
    if geom["type"] == "Polygon":
        return geom["coordinates"]
    out = []
    for poly in geom["coordinates"]:
        out.extend(poly)
    return out


def main():
    data = json.load(open(SRC))
    path_parts = []
    kept = dropped = 0

    for feat in data["features"]:
        for ring in rings(feat["geometry"]):
            pts = []
            for lon, lat in ring:
                if lat < LAT_BOT:
                    continue
                pts.append(project(lon, min(lat, LAT_TOP)))
            if len(pts) < 4:
                continue
            xs = [p[0] for p in pts]
            ys = [p[1] for p in pts]
            if (max(xs) - min(xs)) < MIN_EXTENT and (max(ys) - min(ys)) < MIN_EXTENT:
                dropped += 1
                continue
            simple = rdp(pts, TOL)
            if len(simple) < 3:
                continue
            kept += 1
            cmd = "M" + " ".join(f"{x:.1f} {y:.1f}" for x, y in simple)
            path_parts.append(cmd)

    d = " ".join(path_parts)
    lo = min(miller_y(LAT_BOT), miller_y(LAT_TOP))
    hi = max(miller_y(LAT_BOT), miller_y(LAT_TOP))
    pad = 6.0
    vb_y = lo - pad
    vb_h = (hi - lo) + pad * 2

    with open(OUT, "w") as f:
        f.write(
            "/* GENERATED by tools/make-worldmap.py — do not edit by hand.\n"
            "   Natural Earth 1:110m land, Miller projection, simplified for use\n"
            "   as a low-contrast atmosphere layer. Regenerate with that script. */\n\n"
            f"export const WORLD_VIEWBOX = '0 {vb_y:.1f} {W:.0f} {vb_h:.1f}';\n\n"
            f"export const WORLD_LAND =\n  '{d}';\n"
        )

    print(f"rings kept: {kept}  (dropped as sub-pixel: {dropped})")
    print(f"path chars: {len(d)}  ({len(d)/1024:.1f} KB)")
    print(f"viewBox: 0 {vb_y:.1f} {W:.0f} {vb_h:.1f}")


if __name__ == "__main__":
    main()
